# Generated by Django 5.2.7 on 2026-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatueOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('reference_image', models.ImageField(upload_to='statue_orders/')),
                ('size', models.CharField(choices=[('SMALL', 'Small (4 inches)'), ('MEDIUM', 'Medium (8 inches)'), ('LARGE', 'Large (12 inches)'), ('XL', 'Extra Large (18 inches)')], default='MEDIUM', max_length=10)),
                ('material', models.CharField(choices=[('PLA', 'PLA Plastic'), ('RESIN', 'Resin'), ('SANDSTONE', 'Sandstone')], default='PLA', max_length=15)),
                ('color_preference', models.CharField(blank=True, help_text='Preferred color or finish', max_length=100)),
                ('special_instructions', models.TextField(blank=True, help_text='Any extra details or instructions')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('QUOTED', 'Price Quoted'), ('CONFIRMED', 'Confirmed'), ('PRINTING', 'Printing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '3D Statue Order',
                'verbose_name_plural': '3D Statue Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
